# Homework 1
## Javier Palomares
### September 22, 2019

## Problem 1

1. Watch: Vectors, what even are they? | Essence of linear algebra, Chapter 1 https://www.
youtube.com/watch?v=fNk_zzaMoSs
2. Chapter 2 https://www.youtube.com/watch?v=k7RM-ot2NWY
In this video, in Minute 2:51, two vectors are written by their coordinates. Compute the
coordinates of the vector that is the sum of twice the first (left one) plus the second (right
one).

import numpy as np
first = np.array([-.8,1.3]);
second = np.array([3.1,-2.9]);
coordinates = 2*first + second
print(np.asarray(coordinates))

Are the vectors $[1,1]$, $[1,0]$, $[0,1]$ linearly dependent?
Write the third as a linear combination of the first two.

The vector are not linearly independent. $[1,1]$ can be written as $[1,0] + [0,1]$ so it's a linear combination of the other two.
The third can be written as <br> $[0,1] = [1,1] - [1,0]$

3. Chapter 3 https://www.youtube.com/watch?v=kYB8IZa5AuE
At minute 6:36, a Matrix and a vector is given. Write down how this matrix transforms this
vector. Based on what you learned, write a matrix that rotates the 2D space by 90 degrees
clockwise.

In [26]:
A = np.array([[3, 2],
              [-2, 1]])
v = np.array([5,7])
np.matmul(A,v)

array([29, -3])

The matrix transforms the vector $[5,7]$ to $5 * [3,-2] + 7*[2,1]$ The matrix transforms vectors to linear combinations of $[3,-2]$ and $[2,1]$

The matrix $
\left(\begin{array}{cc} 
0 & 1\\
-1 & 0
\end{array}\right)$ rotates the 2D space by 90 degrees
clockwise.

4. Chapter 4 https://www.youtube.com/watch?v=XkY2DOUCWMU
At 3.34 a composition matrix is shown. Apply this Composition linear transformation to the
vector [1; 2]T and write the transformed vector.

In [37]:
composition_matrix= np.array([[1, -1],
              [1, 0]]);
v = np.array([1,2]);
np.matmul(composition_matrix,v)

array([-1,  1])

5. The determinant | Essence of linear algebra, chapter 6 https://www.youtube.com/watch?v=Ip3X9LOh2dk
In 9.40 there is a quiz question: Write your answer one sentence.

TODO: Finish this

6. Dot products and duality | Essence of linear algebra, chapter 9 https://www.youtube.com/watch?v=LyGKycYT2v0

Project the vector [1; 2; 3]T on the vector [1,1,1]. Write the projected vector.


TODO: Finish

Project the vector [1; 2; 3]T on the span of the vectors [1; 0; 0]T and [1; 0; 0]T . Write the
projected vector.

TODO: There is an error here

## Problem 2: Linear Algebra in Python. 
You can use all Python functions to solve this problem.

1. Consider the linear subspace $S = span(v1, v2, v3, v4)$ where $v1 = [1; 2; 3; 4]; v2 = [0; 1; 0; 1]; v3 =
[1; 4; 3; 6]; v4 = [2; 11; 6; 15]$. 

In [42]:
v1 = np.array([1,2,3,4])
v2 = np.array([0,1,0,1])
v3 = np.array([1,4,3,6])
v4 = np.array([2,11,6,15])

Create a vector inside S different from v1; v2; v3; v4. 

In [45]:
v1+v2+4*v3

array([ 5, 19, 15, 29])

Create a vector not in S.

TODO: Finish

How would you check if a new vector is in S?

A vector $v$ is in S if there a consistent solution $a,b,c,d$ to $v = a * v1 + b * v2 + c * v3 + d * v4$

2. Find the dimension of the subspace S.