# Homework 1
## Javier Palomares
### September 22, 2019

## Problem 1

1. Watch: Vectors, what even are they? | Essence of linear algebra, Chapter 1 https://www.youtube.com/watch?v=fNk_zzaMoSs
2. Chapter 2 https://www.youtube.com/watch?v=k7RM-ot2NWY
In this video, in Minute 2:51, two vectors are written by their coordinates. Compute the
coordinates of the vector that is the sum of twice the first (left one) plus the second (right
one).

In [92]:
import numpy as np
first = np.array([-.8,1.3]);
second = np.array([3.1,-2.9]);
coordinates = 2*first + second
print(np.asarray(coordinates))

[ 1.5 -0.3]


Are the vectors $[1,1]$, $[1,0]$, $[0,1]$ linearly dependent?
Write the third as a linear combination of the first two.

The vector are not linearly independent. $[1,1]$ can be written as $[1,0] + [0,1]$ so it's a linear combination of the other two.
The third can be written as <br> $[0,1] = [1,1] - [1,0]$

3. Chapter 3 https://www.youtube.com/watch?v=kYB8IZa5AuE
At minute 6:36, a Matrix and a vector is given. Write down how this matrix transforms this
vector. Based on what you learned, write a matrix that rotates the 2D space by 90 degrees
clockwise.

In [26]:
A = np.array([[3, 2],
              [-2, 1]])
v = np.array([5,7])
np.matmul(A,v)

array([29, -3])

The matrix transforms the vector $[5,7]$ to $5 * [3,-2] + 7*[2,1]$ The matrix transforms vectors to linear combinations of $[3,-2]$ and $[2,1]$

The matrix $
\left(\begin{array}{cc} 
0 & 1\\
-1 & 0
\end{array}\right)$ rotates the 2D space by 90 degrees
clockwise.

4. Chapter 4 https://www.youtube.com/watch?v=XkY2DOUCWMU
At 3.34 a composition matrix is shown. Apply this Composition linear transformation to the
vector [1; 2]T and write the transformed vector.

In [37]:
composition_matrix= np.array([[1, -1],
              [1, 0]]);
v = np.array([1,2]);
np.matmul(composition_matrix,v)

array([-1,  1])

5. The determinant | Essence of linear algebra, chapter 6 https://www.youtube.com/watch?v=Ip3X9LOh2dk
In 9.40 there is a quiz question: Write your answer in one sentence.

TODO: Finish this

6. Dot products and duality | Essence of linear algebra, chapter 9 https://www.youtube.com/watch?v=LyGKycYT2v0

Project the vector [1; 2; 3]T on the vector [1,1,1]. Write the projected vector.

In [81]:
a = np.array([1,2,3])
b = np.array([1,1,1])
proj_a_b = np.dot(a,b) / np.linalg.norm(b) * b
print(proj_a_b)

[3.46410162 3.46410162 3.46410162]


Project the vector [1; 2; 3]T on the span of the vectors [1; 0; 0]T and [1; 0; 0]T . Write the
projected vector.

TODO: There is an error here

## Problem 2: Linear Algebra in Python. 
You can use all Python functions to solve this problem.

1. Consider the linear subspace $S = span(v1, v2, v3, v4)$ where $v1 = [1; 2; 3; 4]; v2 = [0; 1; 0; 1]; v3 =
[1; 4; 3; 6]; v4 = [2; 11; 6; 15]$. 

In [42]:
v1 = np.array([1,2,3,4])
v2 = np.array([0,1,0,1])
v3 = np.array([1,4,3,6])
v4 = np.array([2,11,6,15])

Create a vector inside S different from v1; v2; v3; v4. 

In [45]:
v1+v2+4*v3

array([ 5, 19, 15, 29])

Create a vector not in S.

$[0,0,0,1]$ is a vector not in $S$. It cannot be writtend as a linear combination of $v1,v2,v3,$ and $v4$

How would you check if a new vector is in S?

A vector $v$ is in S if there a consistent solution $a,b,c,d$ to $v = a * v1 + b * v2 + c * v3 + d * v4$

2. Find the dimension of the subspace S.

In [53]:
M = np.matrix([v1,v2,v3,v4]).transpose()

In [57]:
import sympy
_, inds = sympy.Matrix(M).T.rref() 
inds

(0, 1)

The first 2 vectors are linearly independent. The other 2 are linear combinations of the first 2. So the dimension of S is 2.

3. Find an orthonormal basis for the subspace S.

Since the first 2 vectors are independent, they form the basis for $S$. To find an orthonormal basis, we need to decompose $v_1$ and $v_2$ into orthonormal vectors $n_1$ and $n_2$

I'll let $n_1=\frac{v_2}{|v2|}$ then we need $n_2=a v_1+b v_2$ so that $n_1^T n_2 =0$ 

In [61]:
n1 = v2 /np.linalg.norm(v2)

Since we need $n_1^T n_2 =0$ we end up with needing a solution to $3a +b = 0$.
I'll use $a = -1, b = 3$ then normalize $n_2$

In [70]:
a = -1
b = 3
n2 = a *v1 + b * v2
n2 = n2/ np.linalg.norm(n2)

An orthonal basis for S is given by span(n1,n2)


In [78]:
print(n1)
print(n2)

[0.         0.70710678 0.         0.70710678]
[-0.28867513  0.28867513 -0.8660254  -0.28867513]


4. Solve the optimization problem $min_{x \epsilon S} ||x - z^*||_2$ where $z^* = [1, 0, 0, 0]$.

Since $x$ is in $S$, we can express x as $x = a n_1 + b n_2$
Then the optimization is to minimize

$$f = ||a n_1 + b n_2 - z^*||_2$$

$$f=|| a 
\left(\begin{array}{c} 
0 \\
1 \\
0 \\
1
\end{array}\right)
+ b 
\left(\begin{array}{c} 
-1 \\
1 \\
-3 \\
-1
\end{array}\right)
-
\left(\begin{array}{c} 
1 \\
0 \\
0 \\
0
\end{array}\right)
 || _2 $$
 
 
 $$f=|| 
\left(\begin{array}{c} 
-b-1 \\
a+b \\
-3b \\
a-b
\end{array}\right)
 || _2 $$

We can optimize $F=f^2$ to also find the optimum of $f$.
Taking the gradient of F, we find 

 $$\nabla F=
\left(\begin{array}{c} 
4a \\
22b +2 
\end{array}\right)
 $$
 Setting equal to zero, we find $a = 0, b = \frac{-1}{11}$
 So the optimal solution is at <br> $x = \frac{-1}{11}
\left(\begin{array}{c} 
-1 \\
1 \\
-3 \\
-1
\end{array}\right)$ 

5. (Tricky) Is there a relation of this optimization problem with linear regression? Discuss.

TODO: Finish

## Problem 3: Starting supervised learning in Kaggle.

1. Lets start with our first Kaggle submission in a playground regression competition. Make
an account to Kaggle and find https://www.kaggle.com/c/house-prices-advanced-regression-techniques/

2. Follow the data preprocessing steps from
https://www.kaggle.com/apapiu/house-prices-advanced-regression-techniques/regularized-linear-models.
Then, split the data into a train and test set and fit a linear regression model (without any
regularization) to make predictions. Report the performance (RMSE) of this model on the
train set, the test set and on the Kaggle private leader board.
(Hint: remember to exponentiate np.expm1(ypred) your predictions).

In [94]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib

import matplotlib.pyplot as plt
from scipy.stats import skew
from scipy.stats.stats import pearsonr


%config InlineBackend.figure_format = 'retina' #set 'png' here when working on notebook
%matplotlib inline

In [ ]:
train = pd.read_csv("../input/train.csv")
test = pd.read_csv("../input/test.csv")